// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID          pgtype.UUID
	Title       string
	Description pgtype.Text
	UserID      pgtype.UUID
	CreatedAt   pgtype.Timestamp
}

type User struct {
	ID           pgtype.UUID
	Email        string
	Name         pgtype.Text
	PasswordHash string
	CreatedAt    pgtype.Timestamp
}
